name: Deploy to GitHub Pages

on:
  repository_dispatch:
    types: [deploy]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from github_blog
        uses: dawidd6/action-download-artifact@v11
        with:
          github_token: ${{ secrets.G_T }}
          repo: geoqiao/github_blog
          workflow: gen_site.yml
          run_id: ${{ github.event.client_payload.run_id }}
          name: github-pages
          path: ./_site

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
